//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid BasicEnemy = new Guid("b84a18f4-e411-4811-a7dc-c5cf5372e71b");
		public static readonly Guid BasicTower = new Guid("4ec1ca6a-6d5e-49a8-9af1-9ec96734ebc5");

    }
}
