//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid Enemy = new Guid("7a7637be-60cb-4739-8bb9-855cbde6eb7f");

    }
}
